wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0.2
aug.wave_aug.noise_prob:
  value: 0.2
latent_noise.sigma_max:
  value: 0.2
loss.jepa.weight:
  value: 9.28329075102486
loss.sigreg.weight:
  value: 1.8807197537143088
loss.stft_weight:
  value: 0.701706852844206
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
