wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0.2
aug.wave_aug.noise_prob:
  value: 0.2
latent_noise.sigma_max:
  value: 0.2
loss.jepa.weight:
  value: 3.442780465482796
loss.sigreg.weight:
  value: 4.482293390503588
loss.stft_weight:
  value: 1.3905085902610594
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
