#!/usr/bin/env bash
# CLAE — fresh GPU VM bootstrap: deps -> creds -> data -> training.
#
# Flow on a newly provisioned instance:
#   git clone <repo> && cd continuous-latent-autoencoder
#   cp .env.example .env && $EDITOR .env     # paste tokens (or export the same vars)
#   tmux new -s train                        # training outlives the SSH session
#   ./setup.sh                               # deps + creds + fetch + train
#
# Flags:
#   --no-train   stop after the dataset fetch (inspect manifests first)
#
# Idempotent: uv sync is incremental, the HF snapshot fetch verifies files it
# already has, and _creds.py is regenerated from the env on every run.
#
# Only HF_TOKEN is required here: training fetches the *packed* dataset repo
# (CLAE_HF_REPO) built once by `make pack-and-push`. Kaggle keys are needed
# only on that prep step, when rebuilding the packed repo from raw sources.
set -euo pipefail
cd "$(dirname "$0")"

NO_TRAIN=0
for arg in "$@"; do
    case "$arg" in
        --no-train) NO_TRAIN=1 ;;
        *) echo "[setup] unknown arg: $arg (supported: --no-train)"; exit 1 ;;
    esac
done

# --- 0. Config: .env file, exported vars win over file values --------------
if [ -f .env ]; then
    echo "[setup] loading .env"
    set -a
    # shellcheck disable=SC1091
    . ./.env
    set +a
fi

: "${CLAE_DATA_ROOT:=$HOME/data/clae}"
: "${CLAE_HF_REPO:=aryanrahman/clae-bengali}"
: "${CLAE_CKPT_REPO:=aryanrahman/clae-bengali-encoder}"
: "${CONFIG:=configs/exp0.yaml}"

if [ -z "${HF_TOKEN:-}" ]; then
    echo "[setup] ERROR: HF_TOKEN is not set. It is required to fetch the packed"
    echo "        dataset repo ($CLAE_HF_REPO). Put it in .env (see .env.example)"
    echo "        or export it, then re-run."
    exit 1
fi

# --- 1. Preflight -----------------------------------------------------------
if command -v nvidia-smi >/dev/null 2>&1; then
    echo "[setup] GPU: $(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader)"
else
    echo "[setup] WARNING: nvidia-smi not found — train.py requires CUDA and will fail."
fi
if [ -z "${TMUX:-}" ] && [ -t 1 ]; then
    echo "[setup] NOTE: not inside tmux/screen — training dies with your SSH session."
fi

# --- 2. Dependencies (uv + locked venv) -------------------------------------
make prepare

# --- 3. Materialize clae_data/_creds.py from the env (gitignored) -----------
cat > clae_data/_creds.py <<EOF
"""Generated by setup.sh from the environment/.env — do not edit or commit."""
from __future__ import annotations

HF_TOKEN = "${HF_TOKEN}"
KAGGLE_USERNAME = "${KAGGLE_USERNAME:-}"
KAGGLE_KEY = "${KAGGLE_KEY:-}"
WANDB_API_KEY = "${WANDB_API_KEY:-}"

CLAE_HF_REPO = "${CLAE_HF_REPO}"
CLAE_CKPT_REPO = "${CLAE_CKPT_REPO}"
CLAE_DATA_ROOT = "${CLAE_DATA_ROOT}"
EOF
echo "[setup] wrote clae_data/_creds.py"

# --- 4. W&B auth (train.py's wandb.init reads the env) ----------------------
if [ -n "${WANDB_API_KEY:-}" ]; then
    export WANDB_API_KEY
else
    export WANDB_MODE=offline
    echo "[setup] WANDB_API_KEY not set -> WANDB_MODE=offline (metrics stay in runs/<id>/logs)"
fi

# --- 5. Data: fetch the packed dataset snapshot ------------------------------
make fetch-data CLAE_DATA_ROOT="$CLAE_DATA_ROOT" CLAE_HF_REPO="$CLAE_HF_REPO"

for m in train.jsonl val.jsonl; do
    if [ ! -s "$CLAE_DATA_ROOT/manifests/$m" ]; then
        echo "[setup] ERROR: $CLAE_DATA_ROOT/manifests/$m missing or empty after fetch."
        exit 1
    fi
done
echo "[setup] manifests: $(wc -l < "$CLAE_DATA_ROOT/manifests/train.jsonl") train rows," \
     "$(wc -l < "$CLAE_DATA_ROOT/manifests/val.jsonl") val rows"

# --- 6. Train ----------------------------------------------------------------
if [ "$NO_TRAIN" = "1" ]; then
    echo "[setup] --no-train: done. Start later with:"
    echo "        make train CLAE_DATA_ROOT=$CLAE_DATA_ROOT CONFIG=$CONFIG"
    exit 0
fi

exec make train \
    CLAE_DATA_ROOT="$CLAE_DATA_ROOT" \
    CONFIG="$CONFIG" \
    TRAIN_EXTRA_ARGS="${TRAIN_EXTRA_ARGS:-}"
