# Allowlist: symbols that look unused to vulture but are called via framework
# magic (torch Module.__call__ -> forward, optimizer/scheduler hooks, argparse
# overrides). Pass this file to vulture so it stops flagging them.
#
# Usage: uvx vulture <targets...> .static-analysis/vulture-allowlist.py

class _Module:
    def forward(self): ...
    def streaming_forward(self): ...
    def extra_repr(self): ...
    def get_init_states(self): ...
    def get_last_lr(self): ...
    def state_dict(self): ...
    def load_state_dict(self): ...
    def step(self): ...
    def step_batch(self): ...
    def step_epoch(self): ...

# argparse override sink — `overrides` collects positional KEY=VALUE pairs
overrides = None
