wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0
aug.wave_aug.noise_prob:
  value: 0
latent_noise.sigma_max:
  value: 0.1
loss.jepa.weight:
  value: 8.454802922309893
loss.sigreg.weight:
  value: 3.4182175742255274
loss.stft_weight:
  value: 2.5261469534197065
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
