wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0.2
aug.wave_aug.noise_prob:
  value: 0
latent_noise.sigma_max:
  value: 0.1
loss.jepa.weight:
  value: 0.24511686628558071
loss.sigreg.weight:
  value: 2.392251686481236
loss.stft_weight:
  value: 4.906420832685391
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
