_base_: configs/exp0.yaml
aug:
  mix:
    enabled: true
    prob: 0.5
    swap_prob: 0.5
loss:
  mix_recon:
    enabled: true
    weight: 1.0
    start_step: 0
  primary:
    enabled: true
    weight: 0.2
