wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0
aug.wave_aug.noise_prob:
  value: 0.2
latent_noise.sigma_max:
  value: 0.05
loss.jepa.weight:
  value: 0.7069853367032355
loss.sigreg.weight:
  value: 0.8619785789974069
loss.stft_weight:
  value: 3.432735721074981
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
