wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0
aug.wave_aug.noise_prob:
  value: 0
latent_noise.sigma_max:
  value: 0.05
loss.jepa.weight:
  value: 8.883863927128225
loss.sigreg.weight:
  value: 2.248435044896702
loss.stft_weight:
  value: 3.7369198732367
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
