import argparse
import json
import pathlib
from collections import defaultdict

def create_clean_manifest(report_path, manifest_path, output_path, min_duration=2.0, max_duration=None):
    """
    Creates a clean manifest based on the audit report.
    report_path: path to the JSONL report generated by audit_datasets.py
    manifest_path: original manifest (used to filter)
    output_path: path to save the clean manifest
    """
    print(f"Loading audit report from {report_path}...")
    
    with open(report_path, 'r') as f:
        report = [json.loads(line) for line in f]
        
    print(f"Total entries in report: {len(report)}")
    
    clean_items = []
    
    for entry in report:
        if entry.get('status') == 'ok':
            # Additional checks
            dur = entry.get('duration', 0.0)
            if min_duration and dur < min_duration:
                continue
            if max_duration and dur > max_duration:
                continue
            clean_items.append(entry['item'])

    print(f"Saving {len(clean_items)} clean entries to {output_path}...")
    with open(output_path, 'w') as f:
        for item in clean_items:
            f.write(json.dumps(item) + "\n")

    print(f"Done.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True, help="Audit report jsonl")
    parser.add_argument("--manifest", required=True, help="Original manifest jsonl")
    parser.add_argument("--out", required=True, help="Clean output manifest")
    parser.add_argument("--min_duration", type=float, default=2.0, help="Min duration in seconds")
    parser.add_argument("--max_duration", type=float, default=None, help="Max duration in seconds")
    
    args = parser.parse_args()
    
    create_clean_manifest(args.report, args.manifest, args.out, args.min_duration, args.max_duration)
