wandb_version: 1

aug.wave_aug.lowpass_prob:
  value: 0.2
aug.wave_aug.noise_prob:
  value: 0
latent_noise.sigma_max:
  value: 0.05
loss.jepa.weight:
  value: 0.39040381438446314
loss.sigreg.weight:
  value: 2.466400615559114
loss.stft_weight:
  value: 3.268619475481121
model.bottleneck.kind:
  value: identity
model.bottleneck.latent_dim:
  value: 256
model.encoder.d_model:
  value: 256
